src/Entity/CodePostal.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CodePostalRepository")
 */
class CodePostal
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(name="code_postal", type="string", length=10, unique=true)
     */
    private $CodePostal;

    /**
     * @var
     * @ORM\OneToMany(targetEntity="App\Entity\User", mappedBy="codepostal")
     * @ORM\JoinColumn(nullable=true)
     */
    private $user;

    /**
     * @return mixed
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * @param mixed $user
     */
    public function setUser($user): void
    {
        $this->user = $user;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCodePostal(): ?string
    {
        return $this->CodePostal;
    }

    public function setCodePostal(int $CodePostal): self
    {
        $this->CodePostal = $CodePostal;

        return $this;
    }

    public function __toString()
    {
        return $this->getCodePostal();
    }
}

src/Entity/Prestataire.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PrestataireRepository")
 */
class Prestataire extends User
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=45)
     */
    private $name;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $telnumber;

    /**
     * @ORM\Column(type="string")
     */
    private $tvanumber;

    /**
     * @ORM\Column(type="string", length=45)
     */
    private $website;

    /**
     * @ORM\Column(length=45, unique=true)
     */
    private $slug;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Image", cascade={"persist", "remove"})
     */
    private $image;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Image", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $logo;

    /**
     * @var ArrayCollection
     * @ORM\OneToMany(targetEntity="App\Entity\Stage", mappedBy="prestataires")
     * @ORM\JoinColumn(nullable=true)
     */
    private $stages;

    /**
     * @var ArrayCollection
     * @ORM\ManyToMany(targetEntity="App\Entity\Service", inversedBy="prestataires")
     * @ORM\JoinColumn(name="service_id",referencedColumnName="id", nullable=true)
     */
    private $services;

    /**
     * Prestataire constructor.
     */
    public function __construct()
    {
        $this->services = new ArrayCollection();
        $this->stages = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getTelnumber(): ?string
    {
        return $this->telnumber;
    }

    public function setTelnumber(?string $telnumber): self
    {
        $this->telnumber = $telnumber;

        return $this;
    }

    public function getTvanumber(): ?string
    {
        return $this->tvanumber;
    }

    public function setTvanumber(string $tvanumber): self
    {
        $this->tvanumber = $tvanumber;

        return $this;
    }

    public function getWebsite(): ?string
    {
        return $this->website;
    }

    public function setWebsite(string $website): self
    {
        $this->website = $website;

        return $this;
    }

    public function getImage(): ?Image
    {
        return $this->image;
    }

    public function setImage(?Image $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getLogo(): ?Image
    {
        return $this->logo;
    }

    public function setLogo(Image $logo): self
    {
        $this->logo = $logo;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getSlug()
    {
        return $this->slug;
    }

    /**
     * @param mixed $slug
     */
    public function setSlug($slug): void
    {
        $this->slug = $slug;
    }

    /**
     * @return Collection|Stage[]
     */
    public function getStages(): Collection
    {
        return $this->stages;
    }


    /**
     * @return ArrayCollection
     */
    public function getService(): ArrayCollection
    {
        return $this->services;
    }

    /**
     * @param Stage $stage
     * @return Stage|ArrayCollection
     */
    public function addStage(Stage $stage): ArrayCollection
    {
        if (!$this->stages->contains($stage)) {
            $this->stages[] = $stage;
            $stage->setPrestataires($this);

        }
        return $this->stages[] = $stage;
    }

    /**
     * @param Stage $stage
     */
    public function removeStage(Stage $stage)
    {
        $this->stages->removeElement($stage);
    }

    /**
     * @param Service $service
     * @return Service|ArrayCollection
     */
    public function addService(Service $service)
    {
        return $this->services[] = $service;
    }

    /**
     * @param Service $service
     */
    public function removeService(Service $service)
    {
        $this->services->removeElement($service);
    }

    /**
     * @return Collection|Service[]
     */
    public function getServices(): Collection
    {
        return $this->services;
    }

    /**
     * @param ArrayCollection $services
     */
    public function setServices(ArrayCollection $services): void
    {
        $this->services = $services;
    }

    /**
     * @param $arg
     * @param EntityManager $em
     * @return mixed
     */
    public function findServicesByPrestataire($arg, EntityManager $em)
    {
         $services = $this->$em->getDoctrine()->getRepository(Prestataire::class, $prestataire);
        return $services->findServiceByPrestataire($arg);
    }

    public function findBySlug($slug){
        return $service = $this->$em->getDoctrine()
            ->getRepository(Prestataire::class)
            ->searchBySlug();
    }

    /**
     * @return mixed
     */
    public function __toString()
    {
        return $this->name;
    }
}

src/Form/PrestataireType.php
<?php

namespace App\Form;

use App\Entity\CodePostal;
use App\Entity\Commune;
use App\Entity\Image;
use App\Entity\Localite;
use App\Entity\Prestataire;
use App\Entity\Service;
use App\Entity\Stage;
use App\Entity\User;
use Faker\Test\Provider\Collection;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PrestataireType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('addressNumber',TextType::class)
            ->add('addressRue',TextType::class)
            ->add('email',emailType::class)
            ->add('banni',TextType::class)
            ->add('inscription',TextType::class)
            ->add('inscriptionDate',dateType::class)
            ->add('password',passwordType::class)
            ->add('confirmPassword',passwordType::class)
            ->add('successAttempt',integerType::class)
            ->add('name',TextType::class)
            ->add('telnumber',TextType::class)
            ->add('tvanumber',TextType::class)
            ->add('website',TextType::class)
            ->add('slug',TextType::class)
            ->add('codepostal',EntityType::class,['class'=>CodePostal::class])
            ->add('localite',EntityType::class,['class'=>Localite::class])
            ->add('commune',EntityType::class,['class'=>Commune::class])
         //   ->add('stages',EntityType::class,['class'=>Prestataire::class])
          //  ->add('services',EntityType::class,['class'=>Prestataire::class])
            ->add('image',EntityType::class,['class'=>Image::class])
            ->add('logo',EntityType::class,['class'=>Image::class])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Prestataire::class,
        ]);
    }
}

src/Controller/PrestataireController.php
<?php

namespace App\Controller;

use App\Entity\Commune;
use App\Entity\Prestataire;
use App\Entity\Service;
use App\Entity\User;
use App\Form\PrestataireType;
use App\Repository\PrestataireRepository;
use App\Repository\CommuneRepository;
use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class PrestataireController extends AbstractController
{
    /**
     * @Route("/prestataire", name="prestataire")
     */
    public function index()
    {
        return $this->render('prestataire/services.html.twig', [
            'controller_name' => 'PrestataireController',
        ]);
    }

    /**
     * @Route("/listprestataire", name="listprestataire")
     */
    public function findSome(){
        $em = $this->getDoctrine()->getManager();
        $prestataire = $em->getRepository(Prestataire::class);
        $listPrestataire = $prestataire->findAll();
        return $this->render('prestataire/list/prestaList.html.twig', [
            'prestataire' => $listPrestataire,
        ]);
    }

    /**
     * @Route("/addprestataire", name="createPrestataire")
     * @param Prestataire $prestataire
     * @param Request $request
     * @param ObjectManager $manager
     * @return RedirectResponse|\Symfony\Component\HttpFoundation\Response
     */
    public function addPrestataire(Prestataire $prestataire, Request $request, ObjectManager $manager){
        if (!$prestataire) {
            $prestataire = new Prestataire();
        }
        $form = $this->createForm(PrestataireType::class);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($prestataire);
            $em->flush();
            return $this->redirectToRoute('listprestataire', ['id' => $prestataire->getId()]);
        }
        return $this->render('prestataire/addPrestaire.html.twig',
            ['formedit' => $form->createView()]
        );
    }

    /**
     * @Route("/prestataire/{slug}", name="detailsPrestataire")
     * @param $slug
     * @return RedirectResponse|\Symfony\Component\HttpFoundation\Response
     */
    public function detailsPrestataire($slug)
    {
        $prestataire = $this->getDoctrine()
                        ->getRepository(Prestataire::class)
                        ->findBySlug($slug);

        if (isset($prestataire) == false) {
            return $this->redirectToRoute('detailsPrestataireErrors');

        } else {
            return $this->render('prestataire/details/prestataireDetails.html.twig',
                ['prestataire' => $prestataire]);
        }
    }

    /**
     * Route("/prestataire/{$id}", name="servicesPrestataire")
     * @param $id
     * @return RedirectResponse|\Symfony\Component\HttpFoundation\Response
     */
    public function getServicesByPrestataire($id){
        $prestataire = $this->getDoctrine()
            ->getRepository(Prestataire::class)
            ->find($id);

        if (isset($prestataire) == false) {
            return $this->redirectToRoute('detailsPrestataireErrors');

        } else {
            $services = $prestataire->getServices();
            return $this->render('prestataire/servicesByPresta.html.twig',
                ['services' => $services]);
        }
    }

    /**
     * @Route("/servicesprestataire/{id}", name="servicesPrestataireId")
     * @param $id
     * @return \Symfony\Component\HttpFoundation\Response
     * this method uses the PrestataireRepository
     */
    public function show($id)
    {
        $prestataire = $this->getDoctrine()
            ->getRepository(Prestataire::class)
            ->findOneByIdJoinedToServices($id);

        $services = $prestataire->getServices();
        return $this->render('prestataire/servicesByPresta.html.twig',
            ['services' => $services]);

    }

    /**
     * @Route("/searchPrestataire", name="searchprestataire")
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function recherchePrestaires(Request $request)
    {
        $doctrine = $this->getDoctrine();
        $repoCommunes = $doctrine->getRepository(Commune::class);
        $repoServices = $doctrine->getRepository(Service::class);
        $repoPrestataire = $doctrine->getRepository(Prestataire::class);
        $communes = $repoCommunes->findAll(); // request from CommuneRepository
        $services = $repoServices->findAll(); // request from ServiceRepository
        $prestataires = $repoPrestataire->findAll(); // request dans repo Prestataire

        return $this->render('prestataire/list/recherchePrestataire.html.twig', [
            'prestataires'=>$prestataires,
            'services'=>$services,
            'communes'=>$communes
        ]);
    }

}

templates/prestataire/details/prestataireDetails.html.twig
{# Prestatire Details  #}
{% extends '/prestataire/layoutPrestataire.html.twig' %}

{% block details %}

    <div class=document-title">
        <h1>Prestataire</h1>
    </div>

    <div class="container">
        <div class="row">
            <div class="post" style="margin-bottom: 15px">
                <div class="post-image">
                    {% if prestataire[0].logo is not empty %}
                    <div class="col-sm-6">
                        <div class="posts">
                            <div class="post" style="margin-bottom: 15px">
                                <div class="post-image">
                                    <div class="" style="background-image: url({{ prestataire[0].logo.image }});">
                                        {% else %}
                                        <div class=""
                                             style="background-image: url({{ asset('assets/img/tmp/detail-banner-1.jpg') }});">
                                            {% endif %}

                                            <div>
                                                <h2 class="detail-title">
                                                    {{ prestataire[0].name }}
                                                </h2>
                                                <div class="post-image">
                                                    {% for s in prestataire[0].services %}
                                                        <a href="{{ path('serviceDetails',{'slug':s.slug}) }}">
                                                            <div class="detail-label">{{ s.name }}</div>
                                                        </a>
                                                    {% endfor %}
                                                </div><!-- /.detail-banner-info -->

                                                <div class="">
                                                    <i class="fa fa-map-o"></i>{{ prestataire[0].addressRue }} {{ prestataire[0].addressNumber }}
                                                    ,
                                                    {% if prestataire[0].codePostal is not empty %} {{ prestataire[0].codePostal.codePostal }}{% endif %}
                                                    {% if prestataire[0].commune is not empty %}{{ prestataire[0].commune.commune }}{% endif %}
                                                </div><!-- /.detail-banner-address -->
                                            </div><!-- /.detail-banner-left -->
                                        </div><!-- /.container -->
                                    </div><!-- /.detail-banner -->
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-row">
                        <table id="services" class="table table-striped">
                            <tr>
                                <th>service</th>
                                <th>description</th>
                                <th>Web Site </th>
                            </tr>
                            {% if prestataire[0].services is empty %}
                                <tr>
                                    <td class="">No service found for this prestataire</td>
                                </tr>
                            {% else %}
                                {% for service in prestataire[0].services %}
                                    <tr>
                                        <td>
                                            <a href="{{ path('detailsPrestataire', {'slug':prestataire[0].slug}) }}">
                                                {{ service.name }}
                                            </a>
                                        </td>
                                        <td>{{ service.description }}</td>
                                        <td>
                                            <a href="{{ prestataire[0].website }}">{{ prestataire[0].website }}</a>
                                        </td>

                                    </tr>
                                {% endfor %}
                            {% endif %}
                        </table>
                    </div>
                </div><!-- /.container -->
            </div><!-- /.container -->
        </div>
    </div>
{% endblock %}