src/Entity/Service.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Faker\Test\Provider\Collection;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ServiceRepository")
 */
class Service
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=45)
     */
    private $Name;

    /**
     * @ORM\Column(type="boolean")
     */
    private $EnAvant;

    /**
     * @ORM\Column(type="boolean")
     */
    private $Valide;

    /**
     * @ORM\Column(type="string", length=128, nullable=true)
     */
    private $Description;

    /**
     * @ORM\Column(length=45, unique=true)
     */
    private $slug;

    /**
     * @ORM\ManyToMany(targetEntity="Prestataire", mappedBy="services", cascade={"persist"})
     * @ORM\JoinColumn(name="prestataire_id",referencedColumnName="id",nullable=true)
     */
     private $prestataires;


    public function __construct()
    {
        $this->prestataires = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getEnAvant(): ?bool
    {
        return $this->EnAvant;
    }

    public function setEnAvant(bool $EnAvant): self
    {
        $this->EnAvant = $EnAvant;

        return $this;
    }

    public function getValide(): ?bool
    {
        return $this->Valide;
    }

    public function setValide(bool $Valide): self
    {
        $this->Valide = $Valide;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(?string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getSlug()
    {
        return $this->slug;
    }

    /**
     * @param mixed $slug
     */
    public function setSlug($slug): void
    {
        $this->slug = $slug;
    }

    /**
     * @return Prestataire[]|ArrayCollection|Collection
     */
    public function getPrestataire()
    {
        return $this->prestataires;
    }

    /**
     * @param Prestataire $prestataire
     * @return Prestataire
     */
    public function addPrestataire(Prestataire $prestataire){
        return $this->prestataires[] = $prestataire;
    }

    /**
     * @param Prestataire $prestataire
     */
    public function removePrestataire(Prestataire $prestataire){
        $this->prestataires->removeElement($prestataire);
    }

    public function searchBySlug($slug){
        return $service = $this->$em->getDoctrine()
            ->getRepository(Service::class)
            ->findBySlug();
    }

    /**
     * @return mixed
     */
    public function servicesByPrestataire()
    {
        return $this->services = $this->getRepository()->servicesbyPrestataire();
    }

    /**
     * @return mixed
     */
    public function __toString() {
        return $this->Name;
    }
}

src/Controller/ServiceController.php
<?php

namespace App\Controller;

use App\Entity\Prestataire;
use App\Entity\Service;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\ORM\EntityManager;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class ServiceController extends AbstractController
{
    /**
     * @Route("/service", name="service")
     */
    public function index()
    {
        $ems = $this->getDoctrine()->getManager();
        $service = $ems->getRepository(Service::class);
        $services = $service->findAll();
        return $this->render('service/services.html.twig', [
            'service' => $services,
        ]);
    }

    /**
     * @Route("/details_service/{id}", name="service_details")
     */
    public function detailsServiceByIdD($id)
    {
        $services = $this->getDoctrine()
            ->getRepository(Service::class)
            ->find($id);
        if (isset($services) !== false) {
            return $this->render('/service/details/serviceDetails.html.twig', ['service' => $services]);
        } else {
            return $this->redirectToRoute('service');
        }
    }

    /**
     * @Route("/serviceDetails/{slug}", name="serviceDetails")
     * @param $slug
     * @return RedirectResponse|\Symfony\Component\HttpFoundation\Response
     */
    public function detailsService($slug)
    {
        $services = $this->getDoctrine()
            ->getRepository(Service::class)
            ->findBySlug($slug);
        if (isset($services) !== false) {
            return $this->render('/service/details/serviceDescription.html.twig', ['service' => $services]);
        } else {
            return $this->redirectToRoute('service');
        }
    }

    /**
     * @Route("/servicesByPrestataire/{slug}", name="servicesPrestataire")
     * @param $slug
     * @return RedirectResponse|\Symfony\Component\HttpFoundation\Response
     */
    public function listServicesByPrestataire($slug){
        $services = $this->getDoctrine()->getRepository(Prestataire::class);
        $services->findServicesByPrestataire($slug);
        if (isset($services) !== false) {
            return $this->render('/service/details/servicesByPrestaire.html.twig', ['service' => $services]);
        } else {
            return $this->redirectToRoute('service');
        }
    }
}

templates/service/details/details_services.html.twig
{% extends 'base.html.twig' %}
{% block body %}
{% block container %}
    <div class="container">
        <div class="row">
            <div class="col-md-10">
                <h4>{{ service.name }}</h4>
                <hr>
                <ul>
                   {% include('/service/details/serviceDetails.html.twig') %} include
                    {% for serv in service %}
                        <li><a href="{{ path('services_details', {'id':serv.id}) }}"> {{ serv.description }} )
                            </a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
{% endblock %}
{% endblock %}

templates/service/details/serviceDescription.html.twig
{% extends '/service/layout.html.twig' %}
{% block details %}

    <div class="card-row">
        <div>
            <h3>Detail for the following service</h3>
        </div>
        <div class="card-row-inner">
            {% if service[0] is not empty %}
                <div class="card-row-image" style="background-image: url('{{asset('assets/img/tmp/product-1.jpg')}}');">
                    {% if service[0].enAvant == 1 %} {# = enAvant => Affiche étiquette EnAvant#}
                        <div class="card-row-price">
                            Services du mois <i class="fa fa-star"></i>
                        </div>
                    {% endif %}
                </div><!-- /.card-row-image -->
            {% else %}
                <div class="card-row-image" style="background-image: url('{{asset('assets/img/tmp/product-1.jpg')}}')">
                    {% if service[0].enAvant == 1 %} {# = enAvant => Affiche étiquette EnAvant#}
                        <div class="card-row-price">
                            Services du mois <i class="fa fa-star"></i>
                        </div>
                    {% endif %}
                </div><!-- /.card-row-image -->
            {% endif %}
            <div class="card-row-body">
                <h2 class="card-row-title">{{ service[0].Name }}</h2>
                <div class="card-row-content"><p>{{ service[0].description }}</p></div><!-- /.card-row-content -->
            </div><!-- /.card-row-body -->
        </div><!-- /.card-row-inner -->
        <div class="card-row">
            <table id="categories" class="table table-striped">
                <tr>
                    <th>Prestataire</th>
                    <th>Commune</th>
                    <th>Email</th>
                    <th>Web Site </th>
                </tr>
                {% if service[0].prestataire is empty %}
                    <tr>
                        <td class="">No prestataire found for this service</td>
                    </tr>
                {% else %}
                    {% for prestataire in service[0].prestataire %}
                        <tr>
                            <td>
                                <a href="{{ path('detailsPrestataire', {'slug':prestataire.slug}) }}">
                                    {{ prestataire.name }}
                                </a>
                            </td>
                            <td>{{ prestataire.commune }}</td>
                            <td>{{ prestataire.email }}</td>
                            <td>
                                <a href="{{ prestataire.website }}">{{ prestataire.website }}</a>
                            </td>

                        </tr>
                    {% endfor %}
                {% endif %}
            </table>
        </div>
    </div><!-- /.card-row -->
{% endblock %}

templates/service/details/serviceDetails.html.twig
<div class="cards-row">
    <div class="document-title">
        <h1>Details du Service {{ service }}</h1>
    </div>
    <div class="card-row">
        <div class="card-row-inner">
            {% if service is not empty %}
                <div class="card-row-image" style="background-image: url('{{ service.prestataire.image }}');">
                    {% if service[0].enAvant == 1 %} {# = enAvant => Affiche étiquette EnAvant#}
                        <div class="card-row-price">
                            Services du mois <i class="fa fa-star"></i>
                        </div>
                    {% endif %}
                </div><!-- /.card-row-image -->
            {% else %}
                <div class="card-row-image" style="background-image: url('{{asset('assets/img/tmp/product-1.jpg')}}')">
                    {% if service[0].enAvant == 1 %} {# = enAvant => Affiche étiquette EnAvant#}
                        <div class="card-row-price">
                            Services du mois <i class="fa fa-star"></i>
                        </div>
                    {% endif %}
                </div><!-- /.card-row-image -->
            {% endif %}
            <div class="card-row-body">
                <h2 class="card-row-title">{{ service[0].Name }}</h2>
                <div class="card-row-content"><p>{{ service[0].description }}</p></div><!-- /.card-row-content -->
            </div><!-- /.card-row-body -->
        </div><!-- /.card-row-inner -->
    </div><!-- /.card-row -->
    <div class="card-row">
        <table id="services" class="table table-striped">
            <tr>
                <th>Prestataire</th>
                <th>Commune</th>
                <th>Email</th>
                <th>Site Web</th>
            </tr>
            {% if service[0].prestataire is empty %}
                <tr>
                    <td class="">No Prestataire was found for this service</td>
                </tr>
            {% else %}
                {% for prestataire in service[0].prestataire %}
                    <tr>
                        <td>
                            <a href="{{ path('prestataireDetails', {'slug':prestataire.slug}) }}">
                                {{ prestataire.nom }}
                            </a>
                        </td>
                        <td>{{ prestataire.commune }}</td>
                        <td>{{ prestataire.email }}</td>
                        <td>
                            <a href="{{ prestataire.website }}">
                                {{ prestataire.website}}
                        </td>

                    </tr>
                {% endfor %}
            {% endif %}
        </table>
    </div>
</div>

templates/service/details/serviceDetailsPlus.html.twig
{% extends '/service/layout.html.twig' %}
{% block details %}
<div class="container">
    <div class="row">
        <div class="document-title">
            <h1>Liste des</h1>
            <h1>Catégories de Services</h1>
            {# Affichage total objet trouvé #}
            <h2 class="text-center"> X Services trouvés</h2>
        </div>
        {% if services is not empty %}
            {% for p in services %}
                <div class="col-sm-6">
                    <div class="posts">
                        <div class="post" style="margin-bottom: 15px">
                            <div class="post-image">
                                {% if p.enAvant == 1 %} {# = enAvant => Affiche étiquette EnAvant#}
                                    <div class="card-row-price">
                                        Services du mois <i class="fa fa-star"></i>
                                    </div>
                                {% endif %}
                                {% if p.image is not null %}
                                    <img src="{{ p.image }}" style="border: 1px solid black" alt="{{ p.Name }}" width="640" height="125">
                                {% else  %}
                                    <img src="{{ asset('assets/img/tmp/product-11.jpg') }}" alt="{{ p.Name }}">
                                {% endif %}
                                <a class="read-more" href="{{ path('serviceDetails',{'slug':p.slug}) }}">View</a>
                            </div><!-- /.post-image -->

                            <div class="post-content">
                                <div class=""></div><!-- /.post-label -->
                                <div class=""></div><!-- /.post-date -->
                                <h2>{{ p.Name }}</h2>
                                <p>{{ p.description }}</p>
                            </div><!-- /.post-content -->
                        </div><!-- /.post -->

                    </div><!-- /.posts -->
                </div>
            {% endfor %}
        {% else %}
            <div class="caution">
                <h2>{{ error.msg }}</h2>
            </div>
        {% endif %}
    </div><!-- /.row -->
</div><!-- /.container -->
{% endblock %}

templates/service/details/servicesByPrestaire.html.twig
{% extends 'layout.html.twig' %}
{% block details %}
    <div class="col-sm-12">
        <h2 id="reviews"> Services by Prestataire</h2>
        <div class="posts posts-condensed">

            <table id="categories" class="table table-striped">
                <tr>
                    <th>Id</th>
                    <th>Nom</th>
                    <th>Description</th>
                </tr>
                {% if service is empty %}
                    <tr>
                        <td class="pasde">PAS DE CATEGORIES ACTUELLEMENT</td>
                    </tr>
                {% else %}
                    {% for serv in service %}
                        <tr>
                            <td>
                                <div class="roundedImage">
                                    <img src='{{ serv }}' style="height: 40px; width: 40px;">
                                </div><!-- /.user-image -->
                            </td>
                            <td>{{ service.name }}</td>
                            <td>{{ service.description }}</td>
                        </tr>
                    {% endfor %}
                {% endif %}
            </table>

        </div>
    </div>
{% endblock %}